---

#
# Check preconditions, i.e. its a Debian or Ubuntu distribution.
#
- name: Precondition - check Linux distribution
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'
  fail: msg="ERROR - Not operating on Ubuntu/Debian."

- name: Include variables
  include_vars: "main.yml"

- include: setup.yml

- include: secure-installation.yml

- include: databases.yml

- include: users.yml

- include: cleanup.yml

