---

#
# Install Oracle Java 8 SDK
#

- name: Precondition - check Linux distribution
  fail: msg="ERROR - Not operating on Ubuntu/Debian."
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu' 

- name: Add PPA repository for Oracle Java
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{ ansible_distribution_release }} main"

#- name: add ppa repository key
#  apt_key: id=EEA14886 url=hkp://keyserver.ubuntu.com:80 state=present

- name: Add PPA repository key - hack, due to missing hkp support
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

- name: Execute script to automatically accept the JDK license
  shell: echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | sudo /usr/bin/debconf-set-selections

- name: Install Oracle Java 8
  apt: update_cache=yes name=oracle-java8-installer state=present
