---

#
# Check preconditions, i.e. its a Debian or Ubuntu distribution.
#
- name: Precondition - check Linux distribution
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'
  fail: msg="ERROR - Not operating on Ubuntu/Debian."

#
# Create the Ansible user.
#
- name: Create the Ansible user
  user: name=ansible shell=/bin/bash 

#
# Copy the sudoers file such that ansible can execute commands with sudo rights.
#
- name: Create sudoers file for ansible
  copy: src=./ansible dest=/etc/sudoers.d/ansible mode=0440 validate='visudo -cf %s'

#
# Run a local action to get the current user's username.
#
- name: Get the username running the deploy
  sudo: false
  local_action: command whoami
  register: username_on_the_host

#
# Add the current's user ssh key to Ansible's authorized_keys.
# 
- name: Add key
  authorized_key: user=ansible key="{{ lookup('file', '/home/' + username_on_the_host.stdout + '/.ssh/id_rsa.pub') }}"
